# Generated by Django 4.2.2 on 2023-06-15 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField(max_length=255)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=255)),
                ('cellphone1', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disease', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
