# Generated by Django 4.2.2 on 2023-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_cellphone_user_alternativephonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Province',
            field=models.CharField(blank=True, max_length=255, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
    ]
