# Generated by Django 4.2.2 on 2023-08-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_province_user_country_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Province',
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=255, verbose_name='province'),
        ),
    ]
